### ISSUE TITLE
flirt: build for aarch64

### ISSUE THREAD

**Issue by williballenthin** [williballenthin/lancelot#128]
originally reported here: https://github.com/fireeye/capa/issues/683

some potential details here: https://github.com/PyO3/maturin/issues/375#issuecomment-835179297

**Comment by messense** [comment]
This should be easy with [maturin-action](https://github.com/messense/maturin-action)

**Comment by williballenthin** [comment]
that does look very easy, thank you!

**Comment by williballenthin** [comment]
added in [3b2d3fc65216e20028ed12fea145bbb48cc19e3a](https://github.com/williballenthin/lancelot/releases/tag/v0.7.0) via maturin-action as suggested by @messense (thanks!). 

gh actions config is here: https://github.com/williballenthin/lancelot/blob/917580033bd44fa2bb82fab22a337eef7298e9c5/.github/workflows/publish-pypi.yaml
