### ISSUE TITLE
dis: zydis guarantees visible/explicit operands to be first

### ISSUE THREAD

**Issue by williballenthin** [williballenthin/lancelot#130]
referenced here but im not sure where else: https://github.com/zyantific/zydis/issues/189

**Comment by williballenthin** [comment]
since we only care about explicit operands in our analysis, we can stop enumerating once we hit a non-visible operand

**Comment by athre0z** [comment]
> but im not sure where else

It's also stated in this documentation comment here: https://github.com/zyantific/zydis/blob/6a17c48576e1b016ce098c4bdbd001a1403b6a0a/include/Zydis/DecoderTypes.h#L1005-L1007

:-)

**Comment by williballenthin** [comment]
thank you!
